'use client'

import React, { useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Search, BookOpen } from 'lucide-react'

interface GlossaryTerm {
  term: string
  acronym: string
  definition: string
  category: 'Role' | 'Process' | 'Concept' | 'Artifact'
}

const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    term: "Product Manager",
    acronym: "PM",
    definition: "Evolving from coordinators and document-writers to Domain Designers and Strategic Orchestrators. PMs spend less time writing PRDs and more time defining domain models, business constraints, and strategic alignment.",
    category: "Role"
  },
  {
    term: "Product Requirements Document",
    acronym: "PRD",
    definition: "Traditional documentation detailing product features and specifications. Historically written by PMs, but increasingly generated by AI in modern workflows to focus PMs on higher-level strategy.",
    category: "Artifact"
  },
  {
    term: "Product Operations",
    acronym: "ProdOps",
    definition: "The 'connective tissue' bridging product, engineering, customer success, and executive leadership. It acts as an internal platform solving systemic scaling problems and reducing cognitive load on PMs.",
    category: "Process"
  },
  {
    term: "Product Operating Model",
    acronym: "POM",
    definition: "A modern framework requiring transformation in three dimensions: how you build (continuous delivery), how you solve problems (goal-oriented), and how you decide what problems to solve (data-driven strategy).",
    category: "Concept"
  },
  {
    term: "Voice of the Customer",
    acronym: "VoC",
    definition: "A structured intake system merging qualitative customer feedback with hard product analytics. Often categorizes tickets and calculates a 'Friction Score' to prioritize roadmap issues.",
    category: "Process"
  },
  {
    term: "Weekly Business Review",
    acronym: "WBR",
    definition: "A critical coordination ritual and 'exception' system used to flag deviations and create a shared causal model of the business across functions.",
    category: "Process"
  },
  {
    term: "Gemba Walks (Presence)",
    acronym: "Gemba",
    definition: "The practice of leaders 'going to see' the actual work happening to build firsthand intuition and relationships that quantitative dashboards cannot provide.",
    category: "Concept"
  },
  {
    term: "Founder Mode",
    acronym: "Founder Mode",
    definition: "A pathological failure mode where a leader replaces healthy exception/delegation systems entirely with their own presence, ultimately bottlenecking the organization.",
    category: "Concept"
  },
  {
    term: "Compound Engineering",
    acronym: "CE",
    definition: "Designing software systems composed of multiple specialized AI agents, orchestrators, and traditional code, where agents collaborate to solve complex business problems autonomously.",
    category: "Concept"
  },
  {
    term: "Large Language Model",
    acronym: "LLM",
    definition: "Advanced AI models trained on vast amounts of data to understand and generate human-like text, forming the foundation of agentic workflows.",
    category: "Concept"
  }
]

export default function GlossaryPage() {
  const [searchTerm, setSearchTerm] = useState('')

  const filteredTerms = GLOSSARY_TERMS.filter(item => 
    item.term.toLowerCase().includes(searchTerm.toLowerCase()) || 
    item.acronym.toLowerCase().includes(searchTerm.toLowerCase()) ||
    item.definition.toLowerCase().includes(searchTerm.toLowerCase())
  ).sort((a, b) => a.acronym.localeCompare(b.acronym))

  return (
    <div className="flex h-screen overflow-hidden bg-[#f5f4f0] text-[#1b1c20] font-sans">
      <main className="flex-1 min-w-0 flex flex-col overflow-hidden">
        
        {/* UPPER CONSOLE BAR */}
        <header className="h-16 border-b border-black/10 bg-[#f5f4f0]/80 backdrop-blur-md px-8 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2">
            <span className="text-xs uppercase tracking-widest text-[#8a8d94] font-bold">Lahzo Workspace /</span>
            <span className="text-xs font-mono text-blue-600 uppercase tracking-widest font-bold">
              Product Ops Glossary
            </span>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/" className="text-xs font-bold text-[#5c5f66] hover:text-[#1b1c20] transition-colors flex items-center gap-1">
              <ArrowLeft className="w-4 h-4" /> Back to Matrix
            </Link>
            <div className="flex items-center gap-2 text-xs text-[#5c5f66] bg-white border border-black/10 px-4 py-1.5 rounded-full font-mono shadow-sm">
              <span className="w-2 h-2 rounded-full bg-blue-600 shrink-0" />
              <span>Company-Wide View</span>
            </div>
          </div>
        </header>

        {/* VIEW ROUTER CONTAINER */}
        <div className="flex-1 overflow-y-auto py-10">
          <div className="w-full max-w-[94%] mx-auto px-6 flex flex-col gap-10 animate-in fade-in duration-200">
            <div className="text-center max-w-2xl mx-auto flex flex-col gap-3">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold text-violet-600 bg-violet-50 border border-violet-100 mx-auto font-mono uppercase tracking-wider">
                <BookOpen className="w-3.5 h-3.5" />
                <span>Reference Material</span>
              </div>
              <h2 className="text-4xl font-serif font-black tracking-tight text-[#1b1c20] leading-none">
                Product Ops Terminology
              </h2>
              <p className="text-sm text-[#5c5f66]">
                A unified baseline of definitions and acronyms for the Product Operations framework. Ensure everyone speaks the same language.
              </p>
            </div>

            {/* Search Bar */}
            <div className="max-w-xl mx-auto w-full relative">
              <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                <Search className="h-5 w-5 text-gray-400" />
              </div>
              <input
                type="text"
                placeholder="Search acronyms, terms, or concepts..."
                className="block w-full pl-11 pr-4 py-3 bg-white border border-[#d8d6cc] rounded-xl text-sm shadow-sm placeholder-gray-400 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-colors"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>

            {/* Glossary Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-2 max-w-7xl mx-auto w-full">
              {filteredTerms.map((item, idx) => (
                <div key={idx} className="bg-white border border-[#d8d6cc] p-6 rounded-2xl text-left flex flex-col min-h-[220px] hover:border-[#1b1c20]/40 hover:shadow-xl transition-all duration-200 group">
                  <div className="flex justify-between items-start mb-4">
                    <h3 className="text-3xl font-serif font-black text-[#1b1c20] tracking-tight group-hover:text-blue-600 transition-colors">
                      {item.acronym}
                    </h3>
                    <span className="text-[10px] uppercase tracking-wider font-bold text-[#8a8d94] bg-[#f5f4f0] px-2 py-1 rounded">
                      {item.category}
                    </span>
                  </div>
                  <div className="flex-1">
                    <h4 className="text-sm font-bold text-[#1b1c20] mb-2">{item.term}</h4>
                    <p className="text-xs text-[#5c5f66] leading-relaxed">
                      {item.definition}
                    </p>
                  </div>
                </div>
              ))}
              
              {filteredTerms.length === 0 && (
                <div className="col-span-full py-12 text-center text-[#8a8d94] text-sm">
                  No terms found matching "{searchTerm}"
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
